language: python
python:
  - '2.7'

sudo: required
services:
  - docker

before_install:
  - docker pull thejodesterf5/containthedocs:latest

script:
  - ./scripts/run-in-docker.sh ./scripts/sphinx-test-suite.sh

