language: python
sudo: required
services:
- docker
script:
- ./scripts/docker-docs.sh ./scripts/test-docs.sh
deploy:
  provider: s3
  access_key_id:
    - secure: "$S3_ACCESS_ID"
  secret_access_key:
    - secure: "$S3_ACCESS_KEY"
  bucket:
    - secure: "$S3_BUCKET_NAME"
  skip_cleanup: true
  #on:
  #  -tags: true


