kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace:
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id":"",
        "label":"",
        "remark": "Remove AS3 declaration",
        "": {
          "class": "Tenant"
        }
      }
    }
