# for use with the ASP ephemeral store in Kubernetes v1.6 and later
apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5-asp
  # namespace in which the ASP runs (if not default)
  namespace: <namespace>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: f5-asp
  # namespace in which the ASP runs (if not default)
  namespace: <namespace>
subjects:
  - kind: ServiceAccount
    # Name of the ServiceAccount
    name: f5-asp
    # Must be the same namespace defined in the ServiceAccount
    namespace: <namespace>
roleRef:
  kind: ClusterRole
  # "Cluster-admin" provides super-user access to all resources in the cluster;
  # for more restrictive access, try "admin" or "system:node"
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
