apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ing-virtual-hosting
 namespace: default
 annotations:
  # Provide an IP address from the external VLAN on your BIG-IP device;
  # a hostname resolvable by DNS; or use the default IP
  virtual-server.f5.com/ip: "1.2.3.4"
  # Specify the BIG-IP partition where the Controller should create the virtual server.
  virtual-server.f5.com/partition: "k8s"
  # Specify the desired load balancing algorithm
  virtual-server.f5.com/balance: "least-connections-node"
  # Specify the port on which you want to handle requests
  virtual-server.f5.com/http-port: "80"
spec:
 rules:
 # Omit the host name (URL) to match all hosts
 - http:
     # Provide the path to each Service you want to proxy
     paths:
     - path: /app1
       backend:
         serviceName: myService1
         servicePort: 80
     - path: /app2
       backend:
         serviceName: myService2
         servicePort: 80
