apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ing-virtual-hosting
 namespace: default
 annotations:
  # Provide an IP address from the external VLAN on your BIG-IP device;
  # use DNS lookup; or use the default IP
  virtual-server.f5.com/ip: "1.2.3.4"
  # Specify the BIG-IP partition where the Controller should create the virtual server.
  virtual-server.f5.com/partition: "k8s"
  # Specify the desired load balancing algorithm
  virtual-server.f5.com/balance: "least-connections-node"
  # Specify the port on which you want to handle requests
  virtual-server.f5.com/http-port: "80"
spec:
 rules:
 # URL
 - host: site1.example.com
   http:
     # path to Service from URL
     paths:
       - path: /app1
         backend:
           serviceName: myService1
           servicePort: 80
 # URL
 - host: site2.example.com
   http:
     # path to Service from URL
     paths:
       - path: /app2
         backend:
           serviceName: myService2
           servicePort: 80
