apiVersion: v1
kind: Route
metadata:
  name: route-unsecured
  annotations:
    # Specify a supported BIG-IP load balancing mode
    virtual-server.f5.com/balance: fastest-node
    # Provide the name of an existing BIG-IP client SSL profile
    virtual-server.f5.com/clientssl: /Common/client-ssl
    # Provide the name of an existing BIG-IP server SSL profile
    virtual-server.f5.com/serverssl: /Common/server-ssl
    virtual-server.f5.com/health: |
      [
        {
          "path":     "mysite.example.com/app1",
          "send":     "HTTP GET /health/app1",
          "interval": 5,
          "timeout":  10
        }
      ]
spec:
  host: mysite.example.com
  path: "/app1"
  to:
    kind: Service
    name: myService1
