apiVersion: v1
kind: Route
metadata:
  labels:
    name: myService
  name: myService-route-reencrypt
  annotations:
    # See the k8s-bigip-ctlr documentation for information about
    # all Route Annotations
    # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest/#supported-route-annotations
    virtual-server.f5.com/balance: round-robin
    virtual-server.f5.com/clientssl: /Common/client-ssl
spec:
  host: mysite.example.com
  path: "/myApp"
  port:
    targetPort: https
  tls:
    certificate:  |
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
    key:  |
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
    termination: reencrypt
  to:
    kind: Service
    name: myService
    weight: 100
