apiVersion: v1
kind: Route
metadata:
  labels:
    name: myService
  name: myService-route-passthrough
  annotations:
    # See the k8s-bigip-ctlr documentation for information about
    # all Route Annotations
    # https://clouddocs.f5.com/products/connectors/k8s-bigip-ctlr/latest/#supported-route-annotations
    virtual-server.f5.com/balance: least-connections-member
    virtual-server.f5.com/clientssl: /Common/client-ssl
spec:
  host: mysite.example.com
  path: "/myApp"
  port:
    targetPort: 443
  tls:
    termination: passthrough
  to:
    kind: Service
    name: myService

