kind: ConfigMap
apiVersion: v1
metadata:
  name: guestbook-vs
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.0.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "guestbook",
          "servicePort": 3000
        },
        "frontend": {
          "partition": "k8s",
          "mode": "http",
          "balance": "round-robin",
          "virtualAddress": {
            "bindAddr": "10.2.3.2",
            "port": 8080
          }
        }
      }
    }
