apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: f5-asp
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: f5-asp
    spec:
      hostNetwork: true
      containers:
        - name: f5-asp
          image: "store/f5networks/asp:1.0.0"
          args:
            # the config file is loaded from the ConfigMap; it contains the
            # ASP global config
            - --config-file
            - /etc/configmap/asp.config.json
          securityContext:
            privileged: false
          volumeMounts:
          # mount a new directory
          - name: plugin-config
            # the path the directory will be added to; do not change
            mountPath: /var/run/kubernetes/proxy-plugin
            readOnly: true
          # mount a new directory
          - name: asp-config
            # the path the directory will be added to; do not change
            mountPath: /etc/configmap
      # provide the name of the Secret containing the Docker login credentials
      # REQUIRED TO PULL THE ASP IMAGE FROM DOCKER STORE
      imagePullSecrets:
        - name: <my-secret>
      volumes:
        - name: plugin-config
          hostPath:
            path: /var/run/kubernetes/proxy-plugin
        - name: asp-config
          # replace with name of your ASP ConfigMap
          configMap:
            name: f5-asp-config
