apiVersion: v1
kind: Service
metadata:
  annotations:
    asp.f5.com/config: |
      {
        "ip-protocol": "http",
        "load-balancing-mode": "round-robin",
        "flags" : {
          "x-forwarded-for": true,
          "x-served-by": true
        }
      }
  labels:
    name: frontend
  name: frontend
  namespace: k8petstore
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      port: 80

