apiVersion: v1
kind: Service
metadata:
  annotations:
    # provide the desired ASP config parameters as a JSON blob
    asp.f5.com/config: |
      {
        "ip-protocol": "http",
        "load-balancing-mode": "round-robin",
        "flags" : {
          "x-forwarded-for": true,
          "x-served-by": true
        }
      }
  labels:
    # the name of the Service
    name: myService
  # the name of the Service
  name: myService
  # the namespace of the Service you want to proxy; the ASP pod will be
  # created in this namespace
  namespace: default
spec:
  selector:
    # once again, the name of the Service
    app: myService
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      port: 80

