apiVersion: v1
kind: Service
metadata:
  annotations:
    # provide the desired ASP config parameters as a JSON blob
    # The JSON below provides examples for the ASP virtual server configuration
    # parameters available in v1.1.0
    asp.f5.com/config: |
      {
        "ip-protocol": "http",
        "load-balancing-mode": "round-robin",
        "event-handlers" : [
          {
            "http-request": "module.exports = (req, res, next) => {\n if (req.method === 'POST') {\n res.statusCode = 503;\n res.end('POST Method not supported');\n } else { \n next(); \n } \n}\n"
          },
          {
            "http-response": "module.exports = (res, next) => { res.headers['x-my-bar'] = 'foo'; next(); }"
          }
        ],
        "flags" : {
          "x-forwarded-for": true,
          "x-served-by": true
        },
        "health-monitor": {
          "health-checks": {
            "srv1-check": {
              "default-state": "unknown",
              "active": {
                "timeout": 10,
                "interval": 10,
                "up-count": 2,
                "down-count": 3,
                "http": {
                  "path": "/healthz"
                }
              }
            }
          }
        },
      }
  labels:
    # the name of the Service
    name: myService
  # the name of the Service
  name: myService
  # the namespace of the Service you want to proxy; the ASP pod will be
  # created in this namespace
  namespace: default
spec:
  selector:
    # once again, the name of the Service
    app: myService
  type: NodePort
  ports:
    - name: "http"
      protocol: TCP
      port: 80

