apiVersion: v1
kind: Secret
metadata:
  name: f5-docker-images
  namespace: kube-system
data:
  .dockerconfigjson: ewoJImF1dG[...]NqcGpPVVJVUzNSQlZuUXlaSGM9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
