apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      containers:
        - name: k8s-bigip-ctlr
          # replace the version as appropriate
          # (e.g., f5networks/k8s-bigip-ctlr:1.1.0-beta)
          image: "f5networks/k8s-bigip-ctlr:1.0.0"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=10.190.24.171",
            "--bigip-partition=kubernetes",
            # To manage a single namespace, enter it below
            # (required in v1.0)
            # To manage all namespaces, omit the `namespace` entry
            # (default as of v1.1-beta)
            # To manage multiple namespaces, enter a comma-separated list below
            # (as of v1.1-beta)
            "--namespace=default",
          ]
      imagePullSecrets:
        - name: f5-docker-images
