apiVersion: v1
kind: ClusterRoleBinding
metadata:
    name: bigip-ctlr-role
userNames:
- system:serviceaccount:default:bigip-ctlr
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: bigip-ctlr
roleRef:
  name: system:bigip-ctlr
