apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: f5networks/f5-kube-proxy:v1.0.0
    # do not change the args below if your master kube-proxy settings differ
    # from those shown here
    command:
    - /proxy
    - --master=http://127.0.0.1:8080
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    # add this volumeMount
    - mountPath: /var/run/kubernetes/proxy-plugin
      name: plugin-config
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  # add this volume
  - name: plugin-config
    hostPath:
      path: /var/run/kubernetes/proxy-plugin
