apiVersion: v1
kind: Route
metadata:
  labels:
    name: myService
  name: myService-route-reencrypt
  namespace: default
spec:
  host: mysite.example.com
  path: "/myApp"
  port:
    targetPort: https
  tls:
    certificate:  |
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
    key:  |
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      [...]
      -----END CERTIFICATE-----
    termination: reencrypt
  to:
    kind: Service
    name: myService
    weight: 100
