kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-resource-vs-example
  namespace: default
  labels: 
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.0.json"
  data: |-
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "my-bigip-partition",
          "virtualAddress": {
            "bindAddr": "1.2.3.4",
            "port": 443
          },
          "sslProfile": {
            "f5ProfileName": "Common/my-ssl-cert"
          }
        },
        "backend": {
          "serviceName": "my-kubernetes-service",
          "servicePort": 443
        }
      }
    }
